services:
  backend:
    build : backend/
    ports:
      - "8083:8083"
    volumes:
      - ./backend:/app
  client_web:
    build: web/
    depends_on:
    - backend
    ports:
      - "8082:8082"
    volumes:
      - ./web/src:/app/src
  mobile:
    build : mobile/
    volumes:
      - ./mobile:/app

      